functionsDirectory = "/Users/alecbeck/Downloads/cintas-lead-form-clean/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/alecbeck/Downloads/cintas-lead-form-clean"
publishOrigin = "config"
functions = "/Users/alecbeck/Downloads/cintas-lead-form-clean/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/submit"
to = "/.netlify/functions/submit-lead"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]